### ISSUE TITLE
Adding support for totalVPN

### ISSUE THREAD

**Issue by mrki0620** [Zomboided/VPN-Manager#1]
Hi Zomboided. I'm a newbee to github, but have quite some experience in java, c++ (server-side, client-side) programming. I signed up for the totalVPN service, which is unfortunatelly NOT supported by the VPN-Manager. I checked on quick the source code (really for 10 minutes) and noticed  configuration files for each VPN provider: I'm willing to prepare the VPN configuration files ca.crt, LOCATIONS.TXT, ta.key, TEMPLATE.TXT (would need to be cheked by you - because the provided ovpn files are for windows installation). The provided locations are available here:
https://pseudio.freshdesk.com/helpdesk/attachments/8005828145
in ovpn files.

I would really KINDLY like to ask you to add support also for totalVPN if possible.
Thanks for your answer.
My email for contact: mrki0620@yahoo.com
Peter

**Comment by Zomboided** [comment]
Fixed in 1.3.0
