### ISSUE TITLE
IPVanish issue

### ISSUE THREAD

**Issue by sunderlandz** [Zomboided/VPN-Manager#2]
Hi Zomboided,

I'm trying to connect with IPVanish and I always get error messages. My login details are correct and I tried several times, but without success.

Best regards.

**Kodi Log**

21:56:11 T:13352 WARNING: CPythonInvoker(22): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
21:56:11 T:13352  NOTICE: VPN Mgr : (platform.py) Testing openvpn with : openvpn
21:56:12 T:13352   ERROR: VPN Mgr : (platform.py) Ran openvpn command and it failed
21:56:12 T:13352  NOTICE: VPN Mgr : (platform.py) VPN log file start >>>
21:56:12 T:13352  NOTICE: VPN Mgr : (platform.py) <<< VPN log file end

**Comment by Zomboided** [comment]
The problem is with openvpn, not with VPN Mgr.  Try running it via a command line.  Depending on the platform you're using, it needs to write a log to /run
